= Deploy with Docker

We will build a Docker image and use it to deploy OFBiz with Docker for production.

.Objectives
* Have a single ofbiz docker image with plugins (default, custom)
* Configuration is external - provide a configuration for your environment
* Use an external database and storage volumes
* Docker image should be immutable
* Any code or plugin changes will need a new image deploy


.Build the ofbiz app and docker image from the tar archive
[source,bash]
--
  ./gradlew clean build
  docker build -f Dockerfile -t ofbiz build/

--

.Download a dependency using maven
[source,bash]
--
mvn org.apache.maven.plugins:maven-dependency-plugin:2.4:get \
-DremoteRepositories=https://repo1.maven.org/ \
-Dartifact=org.postgresql:postgresql:42.2.18 \
-Ddest=lib/postgresql-42.2.18.jar
--

NOTE: Docker allows building from a git or url https://docs.docker.com/engine/reference/commandline/build/ . This could make image building simpler: we could build from a tar.gz source release, a tar.gz binary release or directly from a git branch.


