= Deploy OFBiz using containers

We will build a Docker image and use it to deploy OFBiz with containers for production.

NOTE: I'm using the generic term `containers` to refer to Docker, Podman, ContainerD or any other compatible version.

.Objectives
* Have a single ofbiz container image with plugins (default, custom)
* Configuration is external - provide a configuration for your environment
* Use an external database and storage volumes
* The container image should be immutable / stateless
* Any code or plugin changes will need a new image - that you can build based on the default

== Building OFBiz container image

.Build the ofbiz app and docker/podman image from the tar archive
[source,bash]
--
  ./gradlew clean build
  docker build -f Dockerfile -t ofbiz

--

.Database drivers are downloaded and installed during Docker build
[source,bash]
--
RUN curl https://repo1.maven.org/maven2/org/postgresql/postgresql/${PG_JAR_VERSION}/postgresql-${PG_JAR_VERSION}.jar \
    --output /opt/ofbiz/lib/postgresql-${PG_JAR_VERSION}.jar \
    && curl https://repo1.maven.org/maven2/mysql/mysql-connector-java/${MYSQL_JAR_VERSION}/mysql-connector-java-${MYSQL_JAR_VERSION}.jar \
    --output /opt/ofbiz/lib/postgresql-${MYSQL_JAR_VERSION}.jar
--

NOTE: Docker allows building from a git or url https://docs.docker.com/engine/reference/commandline/build/ . This could make image building simpler: we could build from a tar.gz source release, a tar.gz binary release or directly from a git branch.

== Running OFBiz via docker/podman containers

We are deploying with the following:

* An external database - PostgreSQL
* External configuration files - mounted as volumes


=== Run OFBiz with Apache Derby - Demo

We will create a Docker volume for Derby to store files across container restarts.

.How to start OFBiz using Docker
[source,bash]
--
    # Create the docker volume to persist our data
    docker volume create ofbiz-demo

    # When you need to, remove the docker volume
    docker volume rm ofbiz-demo

    # load initial (demo) data in the volume
    docker run --rm \
      --name ofbiz-demo \
      --volume ofbiz-demo:/opt/ofbiz/runtime \
      ieugen/ofbiz:latest \
      /opt/ofbiz/bin/ofbiz --load-data

    # start ofbiz
    docker run \
        --name ofbiz-demo \
        --volume ofbiz-demo:/opt/ofbiz/runtime \
        -p 8443:8443 \
        -p 8080:8080 \
        -p 8009:8009 \
        ieugen/ofbiz:latest
--

=== Run OFBiz with PostgreSQL

We are going to deploy OFBiz on a remote server using PostgreSQL database.
We can deploy the database inside the container or on the host.

We are going to create a directory `/opt/ofbiz` to keep the configuration files and map them in the container from there.

We will copy the configuration there with `scp`.

We will deploy PostgreSql using a container also. We will initialize it using an initialization script that will create the ofbiz user and database.

We are going to bind both PostgreSQL and OFBiz container to the host networking.
This might not be ideal, but it will work for us.


[source,shell]
--
  mkdir -p /opt/ofbiz
--

=== PostgreSQL preparation

[source,bash]
--
    # Connect to a local postgresql via psql
    sudo -u postgres psql
    # Inside psql
    create user ofbiz with password 'ofbiz';
    create database ofbiz with owner 'ofbiz';
    create database ofbizolap with owner ofbiz;
    create database ofbiztenant with owner ofbiz;

    # List databases
    \l+
    # Quit
    \q
--

NOTE: I'm assuming the database is running on a Debian GNU/Linux system.
You should adapt the commands to your system if that is not the case.

.How to start OFBiz using Docker
[source,bash]
--

    docker volume create ofbiz-netdava-db
    docker volume create ofbiz-netdava

    docker run --detach \
        --name ofbiz-postgres \
        --restart unless-stopped \
        --net=host \
        --volume ofbiz-netdava-db:/var/lib/postgresql/data \
        --volume /opt/ofbiz/initdb:/docker-entrypoint-initdb.d \
        --env POSTGRES_PASSWORD=ofbiz \
        postgres:13


    # Data loading
    docker run --rm \
        --name ofbiz-netdava \
        --net=host \
        --volume /opt/ofbiz/entityengine.postgres.xml:/opt/ofbiz/config/entityengine.xml:ro \
        --volume /opt/ofbiz/security.properties:/opt/ofbiz/config/security.properties:ro \
        --volume ofbiz-netdava:/opt/ofbiz/runtime \
        ieugen/ofbiz:trunk-8 --load-data

    docker run --detach \
        --name ofbiz-netdava \
        --restart unless-stopped \
        --net=host \
        --volume /opt/ofbiz/entityengine.postgres.xml:/opt/ofbiz/config/entityengine.xml:ro \
        --volume /opt/ofbiz/security.properties:/opt/ofbiz/config/security.properties:ro \
        --volume ofbiz-netdava:/opt/ofbiz/runtime \
        ieugen/ofbiz:trunk-8
--

